language: bash
sudo: required

services:
  - docker

env:
  - version: v3.3.0
    citydb_version: v3.3.0-alpine
  - version: v3.3.1
    citydb_version: v3.3.1-alpine
  - version: v3.3.2
    citydb_version: v3.3.1-alpine
  - version: v4.0.0
    citydb_version: devel-alpine
  - version: v4.1.0
    citydb_version: devel-alpine
  - version: v4.2.0
    citydb_version: devel-alpine
  - version: master
    citydb_version: devel-alpine

before_install: 
  - docker build --build-arg citydb_wfs_version=${version} -t tumgis/3dcitydb-wfs:${version} ./${version}

before_script:
  - docker run --name cdb -d tumgis/3dcitydb-postgis:${citydb_version}

script:
  - sleep 30
  - docker run --name wfs -d -p 8765:8080 --link "cdb:cdb" -e "CITYDB_CONNECTION_SERVER=cdb" tumgis/3dcitydb-wfs:${version}
  - sleep 10
  - docker logs wfs
  - curl "http://127.0.0.1:8765/citydb-wfs/wfs?SERVICE=WFS&REQUEST=GetCapabilities" -s | grep '<wfs:WFS_Capabilities'
  
notifications:
    slack: tum-gis:Z32lHXJDXaycOn4643NHSXaT
    on_success: change
    on_failure: always
